name: contacts
description: A new Flutter application.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.9.3
  flutter_google_places: ^0.3.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.6.0
  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  sqflite: ^2.0.1
  http: ^0.13.4
  intl: ^0.17.0

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
